[versions]
minecraft = "20w14infinite"
yarn_mappings = "20w14infinite+build.4"
fabric_loader = "0.16.0"
loom = "1.7-SNAPSHOT"
vineflower = "1.10.1"
atum = "3cd1e301"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
atum = { module = "dev.tildejustin:atum", version.ref = "atum" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
